import DesktopLayout from "@/Layouts/DesktopLayout/DesktopLayout";
import MobileLayout from "@/Layouts/MobileLayout/MobileLayout";
import { detectDevice } from "@/lib/detectDevice";
import type { Metadata } from "next";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "tippy.js/dist/tippy.css";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = await detectDevice();
  return (
    <html lang="en">
      <body>
        {isMobile ? (
          <MobileLayout>{children}</MobileLayout>
        ) : (
          <DesktopLayout>{children}</DesktopLayout>
        )}
      </body>
    </html>
  );
}
